version: "3"

services:


  wordpress:
    image: wordpress:5.5
    container_name: wordpress
    restart: always
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    volumes:
      - ./src:/var/www/html
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}   


  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password  
    container_name: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/configs/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    restart: always
    env_file: .env 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}    


  nginx:
    image: linuxserver/letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/config:/config
      - ./docker/nginx/nginx.conf:/config/nginx/site-confs/default
      - ./docker/nginx/ssl.conf:/config/nginx/ssl.conf
    container_name: nginx
    restart: unless-stopped
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - URL=producto1topicoseafit.gq # debe ser un dominio válido 
      - SUBDOMAINS=www,   # opcional   
      - EMAIL=jssaninv@eafit.edu.co   # debe ser un email válido  
      - VALIDATION=http
      - STAGING=false 
      
      
# Opcional:

# Agregar estas líneas a "docker-compose" para ver la BBDD con Adminer - eliminar # para descomentar:

#  adminer:
#    container_name: adm
#    image: adminer 
#    restart: unless-stopped    
#    depends_on:      
#      - mysql
#    ports:      
#      - "8080:8080"        
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      ADMINER_USERNAME: ${MYSQL_USER}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      ADMINER_PASSWORD: ${MYSQL_PASSWORD} 


